[tool.poetry]
name = "{{ cookiecutter.project_slug }}"
version = "{{ cookiecutter.version }}"
description = "{{ cookiecutter.project_short_description }}"
authors = ["{{ cookiecutter.author }} <{{ cookiecutter.email }}>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pydev-cli = "2.0.0"
{% if cookiecutter.install_ipython_kernel %}ipykernel = "^5.3"{% endif %}

[tool.poetry.extras]
docs = ["mkdocs", "mkdocs-material", "markdown-include", "mkdocstrings"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
