[tool.poetry]
name = "pydev-cli"
version = "1.0.0"
description = "A single python development dependency to rule them all"
authors = ["Guillaume Charbonnier <guillaume.charbonnier@capgemini.com>"]

[tool.poetry.dependencies]
python = "^3.7"
toml = "^0.10.1"
typer = "^0.3.2"
pydantic = "^1.6.1"
black = "^19.10b0"
flake8 = "^3.8.3"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
isort = "^5.5.1"
pre-commit = "^2.7.1"
python-semantic-release = "^7.3.0"
mypy = "^0.790"
mkdocs = { version = "^1.1.2", optional = true }
mkdocs-material = { version =  "^6.1.0", optional = true }
markdown-include =  { version ="^0.6.0", optional = true }
mkdocstrings = { version = "^0.13.6", optional = true }

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
docs = ["mkdocs", "mkdocs-material", "markdown-include", "mkdocstrings"]

[tool.poetry.scripts]
pydev = "pydev_cli.cli:app"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
