[tool.poetry]
name = "pycrypter"
version = "0.2.2"
description = ""
authors = ["Bekhs <mypswset@gmail.com>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
