[tool.poetry]
name = "neuroio"
version = "0.0.3"
description = "A Python package for interacting with NeuroIO API"
authors = ["Lev Rubel <l@datacorp.ee>", "Roman Lyalin <rly@datacorp.ee>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
httpx = "^0.16.1"

[tool.poetry.dev-dependencies]
vulture = "^1.0"
bandit = "^1.6"
safety = "^1.8"
isort = "^4.3"
flake8-bugbear = "^19.8"
black = {version = "^18.3-alpha.0", allow-prereleases = true}
mypy = "^0.782.0"
ipython = "^7.7"
pytest = "^5.0"
pytest-asyncio = "^0.12.0"
pytest-cov = "^2.7"
pytest-mock = "^1.10"
respx = "^0.13.0"
pep8-naming = "^0.8.2"
portray = "^1.3.0"
cruft = "^2.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
