[tool.poetry]
name = "u-coreutils"
version = "0.1.1"
description = "GNU coreutils implementation with Python 3.8"
authors = ["duyixian <duyixian1234@qq.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "*"
pylint = "^2.6.0"
mypy = "^0.790"
rope = "^0.18.0"
pytest-cov = "^2.10.1"
pytest-xdist = "^2.1.0"
black = "^20.8b1"

[tool.poetry.scripts]
u-cat = 'u_coreutils.cat:run'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
