[tool.poetry]
name = "getadvice"
version = "0.1.5"
description = "This is a fancy `Hello World` to publishing Python library to PyPi."
authors = ["Rich Leung <kleung.hkg@gmail.com>"]
license = "MIT"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.4"
black = "^20.8b1"
jupyter = "^1.0.0"
ipykernel = "^5.3.4"
nbconvert = "^6.0.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
