[tool.poetry]
name = "fastrepo"
version = "1.4.0"
description = ""
authors = ["gcharbon <guillaume.charbonnier@capgemini.com>"]

[tool.poetry.dependencies]
python = "^3.7"
cookiecutter = "^1.7.2"
typer = "^0.3.2"
pyfiglet = "^0.8.post1"

[tool.poetry.dev-dependencies]
pydev-cli = "2.0.0"

[tool.poetry.scripts]
fastrepo = "fastrepo:app"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
