[build-system]
    build-backend = "poetry.core.masonry.api"
    requires = [
        "poetry-core >= 1.0.0",
        "numpy >= 1.19.0",
    ]

[tool.poetry]
    name = "netatmoqc"
    version = "0.3.3"
    description = "Use machine learning clustering methods to perform quality control over NetAtmo data"
    authors = [
        "Paulo V. C. Medeiros <paulo.medeiros@smhi.se>"
    ]
    license = "MIT"
    readme = "README.md"
    repository = "https://source.coderefinery.org/iOBS/wp2/task-2-3/netatmoqc"
    documentation = "https://source.coderefinery.org/iOBS/wp2/task-2-3/netatmoqc/-/wikis"

[tool.poetry.dependencies]
    attrs = "^20.2.0"
    dash = "^1.13.4"
    dash-daq = "^0.5.0"
    dotmap = "^1.3.17"
    flask-caching = "^1.9.0"
    hdbscan = "^0.8.26"
    humanize = "^2.6.0"
    importlib-metadata = "^1.7.0"
    joblib = "^0.15.1"
    llvmlite = "0.33.^0.dev0" # numba 0.50.1 requires llvmlite <0.34,>=0.33.0.dev0
    mpi4py = {version="^3.0.3", optional=true}
    numba = "^0.50.1"
    numpy = "^1.19.0"
    pandas = "^1.0.5"
    plotly = "^4.8.2"
    psutil = "^5.7.0"
    pyproj = "^2.6.1"
    python = "^3.6.10"
    pytz = "^2020.1"
    redis = "^3.5.3"
    scikit-learn = "^0.23.1"
    # tbb>=2019.5 is needed by numba when using parallel=True in jit
    # This version, however, is not available for sys_platform==darwin (on 2020-08-25)
    tbb = { version = "^2020.0.133", markers = "sys_platform != 'darwin'" }
    toml = "^0.10.1"

[tool.poetry.extras]
    mpi = ["mpi4py"]

[tool.poetry.dev-dependencies]
    black = "^19.10b0"
    pre-commit = "^2.6.0"
    pytest = "^6.0.0"
    pytest-timeout = "^1.4.1"
    tox = "^3.19.0"

[tool.poetry.scripts]
    netatmoqc = "netatmoqc.main:main"

[tool.pytest.ini_options]
    testpaths = "tests"
    addopts = "-v"
    log_cli_level = "INFO"

[tool.black]
    line-length = 79

[tool.tox]
    legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py3{6,8}
skip_missing_interpreters = true

[testenv]
whitelist_externals = poetry
commands =
    rm -f poetry.lock
    poetry install -v
    pytest
"""
