[tool.poetry]
name = "s3-upload-split"
version = "0.1.1"
description = "Streams the content of an iterator to multiple S3 objects based on a regular expression"
authors = ["Cyril Scetbon <cscetbon@gmail.com>"]
homepage = "https://github.com/cscetbon/s3-upload-split"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.15.18"
anypubsub = "^0.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
