[tool.poetry]
name = "ckan_crawler"
version = "0.1.8"
description = ""
authors = ["Lucas Bellomo <lbellomo@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
toml = "^0.10.1"
requests = "^2.24.0"
git-filter-repo = "^2.28.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
ckan_crawler = "ckan_crawler.main:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
